### ISSUE TITLE
PlatformNotSupportedException: Operation is not supported on this platform. (0x80131539)

### ISSUE THREAD

**Issue by scx1125** [InkoreStudios/UI.WPF.Modern#12]
PlatformNotSupportedException: Operation is not supported on this platform. (0x80131539) 不支持.net6吗，我看介绍写着支持

**Comment by NotYoojun** [comment]
可以看看stacktrace吗

**Comment by NotYoojun** [comment]
.net6.0支持的

**Comment by NotYoojun** [comment]
抱歉，由于没有更多信息，我没办法解决这个问题，先关了哈。如果后续有进展的话可以reopen，多谢！

**Comment by NotYoojun** [comment]
好了，请把目标平台设为 10.0.18326.0 或更高。
更多详情可以看 issue #17 (https://github.com/InkoreStudios/UI.WPF.Modern/issues/17)

**Comment by NotYoojun** [comment]
好了，请把目标平台设为 10.0.18326.0 或更高。
更多详情可以看 issue #17 (https://github.com/InkoreStudios/UI.WPF.Modern/issues/17)

@scx1125
