### ISSUE TITLE
托管调试助手 "PInvokeStackImbalance":“对 PInvoke 函数“Inkore.UI.WPF.Modern!Inkore.UI.WPF.Modern.Controls.Primitives.MaximizedWindowFixer::GetWindowPlacement”的调用导致堆栈不对称。原因可能是托管的 PInvoke 签名与非托管的目标签名不匹配。请检查 PInvoke 签名的调用约定和参数与非托管的目标签名是否匹配。”

### ISSUE THREAD

**Issue by scx1125** [InkoreStudios/UI.WPF.Modern#13]
换了.net4.8建的wpf应用，使用UseModernWindowStyle后报错：托管调试助手 "PInvokeStackImbalance":“对 PInvoke 函数“Inkore.UI.WPF.Modern!Inkore.UI.WPF.Modern.Controls.Primitives.MaximizedWindowFixer::GetWindowPlacement”的调用导致堆栈不对称。原因可能是托管的 PInvoke 签名与非托管的目标签名不匹配。请检查 PInvoke 签名的调用约定和参数与非托管的目标签名是否匹配。”

**Comment by NotYoojun** [comment]
> 换了.net4.8建的wpf应用，使用UseModernWindowStyle后报错：托管调试助手 "PInvokeStackImbalance":“对 PInvoke 函数“Inkore.UI.WPF.Modern!Inkore.UI.WPF.Modern.Controls.Primitives.MaximizedWindowFixer::GetWindowPlacement”的调用导致堆栈不对称。原因可能是托管的 PInvoke 签名与非托管的目标签名不匹配。请检查 PInvoke 签名的调用约定和参数与非托管的目标签名是否匹配。”
> 

这个估计是微软api有问题，但是好像不影响使用，可以继续运行

**Comment by NotYoojun** [comment]
You can manually turn the MaximizedWindowFixer by using `ui:WindowHelper.FixMaximizedWindow="False"`

更新到 v0.9.15 版本，然后试试 `ui:WindowHelper.FixMaximizedWindow="False"`
