### ISSUE TITLE
Emoji based Glyphs ?

### ISSUE THREAD

**Issue by Valkirie** [InkoreStudios/UI.WPF.Modern#15]
What would be the best/easier approach to use multi-color emojis instead of Glyphs as part of NavigationViewItem ?
![image](https://github.com/InkoreStudios/UI.WPF.Modern/assets/934757/e0559fa9-9bb7-41d7-a423-196f55d0a751)

**Comment by NotYoojun** [comment]
You may try add an image or SVG graphics using SharpVector lib.

**Comment by Valkirie** [comment]
> You may try add an image or SVG graphics using SharpVector lib. Colored emojis are not supported in wpf.

I'll be trying this : https://github.com/samhocevar/emoji.wpf
