### ISSUE TITLE
System.Windows.Markup.XamlParseException:““初始化“Inkore.UI.WPF.Modern.ThemeResources”时引发了异常。”，行号为“10”，行位置为“18”。

### ISSUE THREAD

**Issue by BoyFaceGirl** [InkoreStudios/UI.WPF.Modern#17]
### **我wpf用的.net core 7如下图**

![image](https://github.com/InkoreStudios/UI.WPF.Modern/assets/8773178/aed4f769-8cbc-4c68-bf7f-7e1a1791b25f)

### **Inkore.UI.WPF.Modern 版本为0.918如下图**

![image](https://github.com/InkoreStudios/UI.WPF.Modern/assets/8773178/4980b5a0-d11b-4d94-84c3-1fc51a87136f)

### **这是mainWindow 的代码**

![image](https://github.com/InkoreStudios/UI.WPF.Modern/assets/8773178/ed228d16-af89-47d2-88a1-781a99894f8d)

### **这是报错信息**
![image](https://github.com/InkoreStudios/UI.WPF.Modern/assets/8773178/cc3f7911-f2cc-440f-a838-0250ea1e3246)

### **这是报错的堆栈信息**

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=“初始化“Inkore.UI.WPF.Modern.ThemeResources”时引发了异常。”，行号为“10”，行位置为“18”。
  Source=PresentationFramework
  StackTrace:
   在 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   在 System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   在 UI.WPF.Modern.App.InitializeComponent() 在 E:\Student\DotNet\WinUI\UI.WPF.Modern\Win11StyleWpf\UI.WPF.Modern\App.xaml 中: 第 1 行
   在 UI.WPF.Modern.App.Main()

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
TypeInitializationException: The type initializer for 'Inkore.UI.WPF.Modern.ThemeManager' threw an exception.

内部异常 2:
TypeInitializationException: The type initializer for 'Inkore.UI.WPF.Modern.ColorsHelper' threw an exception.

内部异常 3:
PlatformNotSupportedException: Operation is not supported on this platform. (0x80131539)

### **这是我测试用的源代码**

[Win11StyleWpf.zip](https://github.com/InkoreStudios/UI.WPF.Modern/files/12586713/Win11StyleWpf.zip)

**Comment by NotYoojun** [comment]
另外，我帮你改了下 MainWindow.xaml 的代码，好让它看起来更好看：

```xml
<Window x:Class="UI.WPF.Modern.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:UI.WPF.Modern"
        mc:Ignorable="d"
        xmlns:ui="http://schemas.inkore.net/lib/ui/wpf/modern"
        Title="MainWindow" Height="450" Width="800"
        ui:WindowHelper.SystemBackdropType="Mica" ui:WindowHelper.UseModernWindowStyle="True" ui:TitleBar.Height="36">
    <Grid>
        <ui:NavigationView IsPaneOpen="False">
            <ui:NavigationView.MenuItems>
                
                <ui:NavigationViewItem Content="Home">
                    <ui:NavigationViewItem.Icon>
                        <ui:FontIcon Glyph="{x:Static ui:SegoeIcons.Home}"/>
                    </ui:NavigationViewItem.Icon>
                </ui:NavigationViewItem>
                <ui:NavigationViewItem Content="Shop">
                    <ui:NavigationViewItem.Icon>
                        <ui:FontIcon Glyph="{x:Static ui:SegoeIcons.Shop}"/>
                    </ui:NavigationViewItem.Icon>
                </ui:NavigationViewItem>

            </ui:NavigationView.MenuItems>
            <ui:NavigationView.FooterMenuItems>

                <ui:NavigationViewItem Content="Settings">
                    <ui:NavigationViewItem.Icon>
                        <ui:FontIcon Glyph="{x:Static ui:SegoeIcons.Settings}"/>
                    </ui:NavigationViewItem.Icon>
                </ui:NavigationViewItem>


            </ui:NavigationView.FooterMenuItems>
        </ui:NavigationView>
    </Grid>
</Window>
```

它看起来应该是这样：

<img width="600" alt="image" src="https://github.com/InkoreStudios/UI.WPF.Modern/assets/54567489/f77a1d7c-27a1-4350-8c83-84e1cf4e5cab">

**Comment by NotYoojun** [comment]
如果问题解决就可以关闭issue了，祝你生活愉快！

**Comment by BoyFaceGirl** [comment]
> 如果问题解决就可以关闭issue了，祝你生活愉快！

限定windows 版本的原因是什么？是因为 mic特效么？如果我不想限定windows版本有没有什么配置可以进行选择？

**Comment by NotYoojun** [comment]
因为里面有一些和winrt的交互，比如主题颜色，mica之类的，所以目标操作系统必须是这个。
不过你可以把最低操作系统（受支持的操作系统）改成7.0，这样在win7和8上也可以运行。

**Comment by BoyFaceGirl** [comment]
> 因为里面有一些和winrt的交互，比如主题颜色，mica之类的，所以目标操作系统必须是这个。 不过你可以**把最低操作系统（受支持的os版本）改成7.0**，这样在win7和8上也可以运行。

额，真的是学无止尽了，wpf 和winrt怎么交互我是真的一点都不懂也不会啊，感谢楼主的开源奉献，为表敬意，小小的支持一下，记住我 github 账号叫 boyfacegirl，刚刚想捐点，但是你给的网站打不开注册不上，建议把收款码铁道 read.md 文件里

**Comment by NotYoojun** [comment]
感谢支持！这是我的赞助页面：
https://inkore.net/about/members/notyoojun#sponsor
