### ISSUE TITLE
Add Support for Strong Name Sign assembly

### ISSUE THREAD

**Issue by ghost1372** [InkoreStudios/UI.WPF.Modern#20]
Please Add Support for Strong named assembly.

**Comment by NotYoojun** [comment]
I will consider this in the future and work on it. This may be applied on the next releases.

**Comment by ghost1372** [comment]
Tnx @NotYoojun 
but did you sign both dll?
i am get exception when i am using in vsix:

System.Windows.Markup.XamlParseException: 'Could not load file or assembly 'iNKORE.UI.WPF.Modern, PublicKeyToken=cd19e634b9706635' or one of its dependencies. The system cannot find the file specified.'

**Comment by NotYoojun** [comment]
This is weird, it works all fine on my computer 😥

**Comment by ghost1372** [comment]
> This is weird, it works all fine on my computer 😥

even in vsix?

**Comment by NotYoojun** [comment]
Sorry, I've never been in any development of VSIXs. I just write regular WPF apps.

**Comment by ghost1372** [comment]
@NotYoojun i fixed issue, i will create a new issue For anyone having this problem
