### ISSUE TITLE
Improve Performance and Simplify Xaml Resources

### ISSUE THREAD

**Issue by ghost1372** [InkoreStudios/UI.WPF.Modern#22]
we can improve Performance and simplify Xaml Resources, I did this for HandyControl and it can improves performance and simplify development and xaml resources.
in WPF We must have only one resource file (containing all resources a single very very large file), otherwise we will suffer from performance loss.  Since it is very difficult to develop the app in only one xaml file, we use MergedDictionary and seperated files.
But what if we use separate files but collect them all in one file? In this case, we have made the development process easier and improved the performance.

we can use a tool called: **XAMLTools.MSBuild**
if you want I can do this and collect all the resources in one file. for this we need to move xaml files in one places, so project structure will be change
let me know if you are agree or not

**Comment by ghost1372** [comment]
by using this tool this kind of refrences will be gone and we dont need them anymore

```
<ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="/iNKORE.UI.WPF.Modern;component/Themes/Styles/Button.xaml" />
        <ResourceDictionary Source="/iNKORE.UI.WPF.Modern;component/Themes/Styles/TextBox.xaml" />
    </ResourceDictionary.MergedDictionaries>


<ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="Button.xaml" />
        <ResourceDictionary>
            <converters:RoundMathConverter x:Key="RoundMathConverter" />
            <converters:RoundRadiusConverter x:Key="RoundRadiusConverter" />
        </ResourceDictionary>
    </ResourceDictionary.MergedDictionaries>
```

**Comment by NotYoojun** [comment]
Sorry, I can't rly understand what u said. Could you be more specific?

Will this tool cause any extra references?

**Comment by ghost1372** [comment]
> Sorry, I can't rly understand what u said. Could you be more specific?
> 
> Will this tool cause any extra references?

This is a msbuild tasks so there is no dll or dependency
Currently you are refrencing styles or converters in each resource dictionary and you are refrencing every dictionary in merged dictionary.
So we have a lot of merged dictionaries, this will lose performance and make app slow for loading styles, we can remove all merged dictionaries and all refrenced converters. We can have a single xaml for converters or other stuffs, this tool can help us read all xaml files exist in our repo and make a single xaml file which contains all our resources/styles this way app will be run faster and style loading will be improved

**Comment by NotYoojun** [comment]
Some dictionaries are dynamically called, like `Light.xaml` and `Dark.xaml` and so on. I'm not sure it can work on this. However maybe you can have a try.

Btw how will it change the project structure?

**Comment by ghost1372** [comment]
> Some dictionaries are dynamically called, like `Light.xaml` and `Dark.xaml` and so on. I'm not sure it can work on this. However maybe you can have a try.
> 
> Btw how will it change the project structure?

Schema will be excluded from merging in a single file. we only merge styles and custom controls and other stuffs like converters...
we can use current structure, but we can make things better, for example we can create a xaml file for Converters, moving all custom control styles in a Folder currently they are seperated in each folder (NavigationView\NavigationView.xaml , InfoBar\InfoBar.xaml)

otherwise we should use a list of exclude options...

**Comment by NotYoojun** [comment]
Pls wait for me to re-organize the Modern.Controls library structure, then you can have a try

**Comment by ghost1372** [comment]
Tnx

**Comment by ghost1372** [comment]
> I think it's wiser to keepn the current folder structure. Can you do that with the folder structure unchanged?

yes, no problem

**Comment by NotYoojun** [comment]
Okay I've merged it

**Comment by ghost1372** [comment]
i created a pr #27  which covers **iNKORE.UI.WPF.Modern**, and i am waiting for you to re-organize **iNKORE.UI.WPF.Modern.Controls**

**Comment by NotYoojun** [comment]
Hi! Sorry to bother you, but there's still an exception keeping throwed. Can you gave a minute to check it out?
Fyi, the latest nuget package also has this issue and doesn't work.

<img width="444" alt="image" src="https://github.com/InkoreStudios/UI.WPF.Modern/assets/54567489/4ab52c02-fb0d-450d-8125-286c27c8abce">

**Comment by NotYoojun** [comment]
Hey @ghost1372 ,I think the current structure of iNKORE.UI.WPF.Modern.Controls is okay and I'm not gonna touch it. You can start it any minute you want.

**Comment by NotYoojun** [comment]
> Hi! Sorry to bother you, but there's still an exception keeping throwed. Can you have a minute to check it out? Fyi, the latest nuget package also has this issue and doesn't work.
> 
> I tried to remove the merged reference in MenuFlyout.xaml, but that doesn't work, either.


This issue only occurs only when the config is set to `Release`

**Comment by ghost1372** [comment]
I strongly suggest that you merge the libraries into a Single Library

**Comment by NotYoojun** [comment]
Thank you so much for working with us these days. So sorry that these don't work. I hope we can collaborate more in the future!
