### ISSUE TITLE
Dropdown won't scroll to selected item if list of elements is long

### ISSUE THREAD

**Issue by Valkirie** [InkoreStudios/UI.WPF.Modern#3]
![image](https://user-images.githubusercontent.com/934757/223766954-306d81f9-5ac9-4ad0-b758-fa9e325a1588.gif)

**Comment by NotYoojun** [comment]
Hi! Thanks for feedback. 

Unfortunately I have no idea how to solve this problem. if there is anyone who would like to help pull requests are welcomed!

**Comment by NotYoojun** [comment]
So sorry, i can't fix this. looking for somebody who can help :(
