### ISSUE TITLE
可否支持更多目标框架 如net7or8

### ISSUE THREAD

**Issue by Zaitonn** [InkoreStudios/UI.WPF.Modern#30]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/InkoreStudios/UI.WPF.Modern/assets/103164490/4042ae6d-c372-4654-b19e-6cb910ad543b)

**Describe the solution you'd like**
~~非常好仓库，但是非常少目标框架，使我困难~~

使用`net6.0-windows`而非`net6.0-windows10.0.18362`是否可行
并支持一下net8可否🥺

**Describe alternatives you've considered**
null

**Additional context**
`iNKORE.UI.WPF.Modern.SampleApp`项目编译有点问题 貌似是没更新

**Comment by NotYoojun** [comment]
我自己电脑上没有装net7和8的sdk，所以不好去编译。
理论上自己下载代码后加上7和8的目标框架是可以编译的。

**Comment by NotYoojun** [comment]
新版是可以直接用 `net6.0-windows` 的，不过要支持主题颜色和深浅模式跟随系统的话，必须要 10.0 的目标框架。
