### ISSUE TITLE
NavigationView下图标大小的问题？

### ISSUE THREAD

**Issue by KirsebaerQAQ** [InkoreStudios/UI.WPF.Modern#9]
![image](https://github.com/InkoreStudios/UI.WPF.Modern/assets/48231006/aa0f1d3c-5664-40a5-b849-5f97204e5eb1)
很奇怪的情况

**Comment by NotYoojun** [comment]
#10

**Comment by NotYoojun** [comment]
现在版本中fonticon的默认大小改成16了

@KirsebaerQAQ
